apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database }}
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.runCommand({ ping: 1 })"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
